language: cpp
dist: trusty
sudo: required
env:
  global:
    - DISPLAY=:99.0
    - PEPPER_VERSION=pepper_47
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - libc6-i386
      - lib32gcc1
      - lib32stdc++6
      - google-chrome-stable
before_install:
  - sh -e /etc/init.d/xvfb start
  # Set Git User
  - git config --global user.name "Travis-CI Bot"
  - git config --global user.email "meowlab@users.noreply.github.com"
  # Install socksify for test
  - sudo apt-get -qq update
  - sudo apt-get install -y dante-client
  - sudo cp tests/socksify/socks.conf /etc
  # Install chrome-driver, shadowsocks-libev and selenium for test
  - sudo tests/crdriver/install.sh
  - sudo tests/ss-libev/install.sh
  - sudo -H pip2 install selenium
install:
  # Install Native Client SDK
  - pushd ~
  - wget http://storage.googleapis.com/nativeclient-mirror/nacl/nacl_sdk/nacl_sdk.zip
  - unzip nacl_sdk.zip
  - cd nacl_sdk
  - ./naclsdk update $PEPPER_VERSION
  - export NACL_SDK_ROOT="`pwd`/$PEPPER_VERSION"
  # Install depot_tools
  - cd ~
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH=`pwd`/depot_tools:"$PATH"
  # Install webports
  - mkdir webports
  - cd webports
  - gclient config --name=src https://chromium.googlesource.com/webports.git
  - gclient sync
  # Install OpenSSL and libsodium to Native Client SDK
  - cd src
  - git checkout $PEPPER_VERSION
  - NACL_ARCH=pnacl make openssl
  - NACL_ARCH=pnacl make libsodium
  - popd
script:
  - make
  - sudo tests/travis.sh
before_deploy:
  - 'tar -czf shadowsocsk-nacl-$TRAVIS_TAG.tar.gz pnacl/**/*.{nmf,pexe,bc} -C src shadowsocks.js'
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: IWHjpv5m/keb/zio7LBFu0p8u/Soo0kJRKtwK2PJPsU28taiZwNN40Fv4BCP1lDVgnVKSqte9+x+6oOnSXYLocRnxQ3tnJziEyxIDWRE0xJdQILzr/HE3tw5lUrrSe9+lIVKchR/57KVbMeZEQrAzp2DHEqYANe6xmOX/kYO6uhpsX3CdPW1XgMMf7necnF1kHqWLPLDEByNfgXd58V9qq97XtqFguvmwKK+X858jBnlYqaMoJVUNS9ggg2gMjaoH+iUj+S56B1eF1tPZcnYMufluhGiTDpPBTBb3dw5gzYOurgauoC3Y1RnVgTvGQsrQQIWLMSoBGYi8cIjike8NYdxiyTN33x1MEUokU0Oys391H8pQR1oua72cvRIu7saldwiKMkRyow8ni3TEleeLHqMywmprn4ZhNUWqPOhVA0J1bFLjgP4TvluabRkBadehDGkeNr0vdXCFoXG0zonPq1nFVMl9V2vs7aPDQlZqSDDNKkDtpjHspVFkc3Vhkooji42ChLIxNlxCg261hs1NR6b643FSh23y8ehRprCadzj85Cb467AKnAOba0LiWVzvYW1fdzVIuYbP+PJNqwMi8AdX7U4Te3ihUPmcGiPClUtpoo5dhzKwqccCos4ga/LCm8Bacp6xOhExZa9bt9oADmsjRuSGdMNV4N0Oy/671M=
  file: shadowsocsk-nacl-$TRAVIS_TAG.tar.gz
  on:
    tags: true
