language: cpp
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - libc6-i386
      - lib32gcc1
      - lib32stdc++6
      - chromium-browser
before_install:
  - git config --global user.name "Travis-CI Bot"
  - git config --global user.email "meowlab@users.noreply.github.com"
  - sudo apt-get -qq update
  - sudo apt-get install -y chromium-chromedriver
  - cd ..
  - git clone https://github.com/shadowsocks/shadowsocks-libev.git
  - cd shadowsocks-libev
  - git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
  - ./configure && make
  - sudo make install
  - cd ../shadowsocks-nacl
install:
  - cd ..
  - wget http://storage.googleapis.com/nativeclient-mirror/nacl/nacl_sdk/nacl_sdk.zip
  - unzip nacl_sdk.zip
  - cd nacl_sdk
  - ./naclsdk update pepper_47
  - export NACL_SDK_ROOT="`pwd`/pepper_47"
  - cd ..
  - git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH=`pwd`/depot_tools:"$PATH"
  - mkdir webports
  - cd webports
  - gclient config --name=src https://chromium.googlesource.com/webports.git
  - gclient sync
  - cd src
  - git checkout pepper_47
  - NACL_ARCH=pnacl make openssl
  - NACL_ARCH=pnacl make libsodium
  - cd ../../shadowsocks-nacl
script:
  - make
